name: ci/cd pipeline to deploy artifact into tomcat
on:
  push:
    branches: master
jobs:
  build-deploy:
     runs-on: ubuntu-latest
     steps:
      - name: checkout code 
        uses: actions/checkout@v5
      - name: set-up jdk 
        uses: actions/setup-java@v5
        with:
           distribution: "temurin"
           java-version:  '17'
      - name: validate with maven
        run: mvn validate

      - name: compile with maven
        run: mvn compile

      - name: test with maven
        run: mvn test

     
      - name: package maven
        run: mvn package

      - name: Verify WAR
        run: |
            echo "Files in target:"
             ls -lh target/
               test -f target/TrainBook-1.0.0-SNAPSHOT.war

     # - name: Test Tomcat
      #  run: |
         # curl -v --connect-timeout 10 \
           #  http://${{ secrets.TOMCAT_HOST }}:8080

      - name: Deploy TrainBook WAR
        run: |
          curl -v \
           -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
           -T "target/TrainBook-1.0.0-SNAPSHOT.war" \
           "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"

      - name: Verify TrainBook deployment
        run: |
          curl -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
          http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/list
